modLoader = "javafml"
loaderVersion = "[31,)"
license = "ISC license"
[[mods]]
modId = "boostboots"
version = "${file.jarVersion}"
displayName = "Boost Boots"
authors = "Frieder Hannenheim"
description = '''
This mod adds Boost Boots™, that let you double jump and fly for a while'''
[[dependencies.boostboots]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.boostboots]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"
[[dependencies.boostboots]]
    modId="curios"
    mandatory=false
    versionRange="[1.15.2-2.0.2.6]"
    ordering="NONE"
    side="BOTH"